version: "3.8"

services:
  roscore:
    image: ros:kinetic
    command: roscore
    container_name: ros_master
    network_mode: host

  vins_fusion:
    image: vins-fusion-rviz
    container_name: vins_fusion_rviz
    depends_on:
      - roscore
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_MASTER_URI=http://localhost:11311
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/Repos_AR/VINS-Fusion:/root/catkin_ws/src
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
